application: watchful-ripple-112520
version: 1
runtime: go
api_version: go1

handlers:
- url: /auth/.*
  script: _go_app
- url: /api/.*
  script: _go_app
- url: /
  static_files: wwwroot/index.html
  upload: wwwroot/index.html
- url: /home
  static_files: wwwroot/index.html
  upload: wwwroot/index.html
- url: /building.*
  static_files: wwwroot/index.html
  upload: wwwroot/index.html
- url: /login.*
  static_files: wwwroot/index.html
  upload: wwwroot/index.html
- url: /
  static_dir: wwwroot