application: watchful-ripple-112520
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: wwwroot/index.html
  upload: wwwroot/index.html
- url: /
  static_dir: wwwroot